return {
    -- {
    --     'L3MON4D3/LuaSnip', 
    --     -- lazy=true,
    --     opts = {
    --         history = true,
    --         updateevents = "TextChanged,TextChangedI"
    --     },
    --     config = function(_, opts)
    --         local ls = require("luasnip")
    --         opts.expand = function(args)
    --             luasnip.lsp_expand(args.body)
    --         end,
    --         ls.setup(opts)
    --         local snip_path = vim.fn.stdpath("config") .. "/snippets"
    --         require("luasnip.loaders.from_lua").lazy_load({ paths = snip_path })
    --         -- ваши маппинги для expand/jump
    --         -- vim.keymap.set({"i", "s"}, "<Tab>", function()
    --         vim.keymap.set({"i", "s"}, "<A-j>", function()
    --             if ls.expand_or_jumpable() then
    --                 ls.expand_or_jump()
    --             end
    --         end, { silent = true })
    --
    --         -- vim.keymap.set({"i", "s"}, "<S-Tab>", function()
    --         vim.keymap.set({"i", "s"}, "<A-k>", function()
    --             if ls.jumpable(-1) then
    --                 ls.jump(-1)
    --             end
    --         end, { silent = true })
    --         
    --     end,
    -- },
    -- {
    --     'saadparwaiz1/cmp_luasnip', 
    --     opts = {},
    --     config = function()
    --         
    --     end,
    --     -- lazy=true,
    -- },
}
